FROM alpine:3.17 AS build
RUN apk add rust cargo
WORKDIR /signal-client
COPY ./signal-client .
RUN cargo build --release

FROM alpine:3.17 AS production
RUN apk add libgcc
COPY --from=build ./signal-client/target/release/signal-client .

CMD watch -n 10 ./signal-client