FROM alpine:3.17 AS build
RUN apk add rust cargo
WORKDIR /signal-server
COPY ./signal-server .
RUN cargo build --release

FROM alpine:3.17 AS production
RUN apk add libgcc
COPY --from=build ./signal-server/target/release/signal-server .

CMD ./signal-server