FROM alpine:3.20 AS build
RUN apk update && apk add rust cargo protobuf-dev
WORKDIR /signal
COPY ./signal .
RUN cargo build --bin client --release

FROM alpine:3.20 AS production
RUN apk update && apk add libgcc
COPY --from=build ./signal/target/release/client .

CMD watch -n 10 ./client