FROM alpine:3.20 AS build
RUN apk update && apk add rust cargo protobuf-dev
WORKDIR /signal
COPY ./signal .
RUN cargo build --bin server --release

FROM alpine:3.20 AS production
RUN apk update && apk add libgcc
COPY --from=build ./signal/target/release/server .

CMD ./server