[package]
name = "analysis"
version = "0.1.0"
edition = "2021"

[dependencies]
pcap = { version= "2.2.0", features = ["capture-stream"] }
libc = "0.2"
rusqlite = { version = "0.32.0", features = ["bundled"] }
ctrlc = "3.4"
